---
title: "Assignment 04"
author: "Ankushi Mitra"
date: "10/10/2021"
output: html_document
urlcolor: blue
---

```{r setup, pagenumbering="arabic", include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = "hide")
```

Dataset sourced from [Afrobarometer (Round 7)](https://afrobarometer.org/data/merged-round-7-data-34-countries-2019).

Codebook sourced from [Afrobarometer](https://afrobarometer.org/sites/default/files/r7_merged.codebook_final_14dec20.pdf).

## Visualization 1

```{r}

library(tidyverse)
library(ggplot2)
library(haven)
library(readxl)
library(scales)


AB <- read_sav("/Users/ankushi/Desktop/GOVT-772_Data_Science/assignment04/AB_R7_Merged")
GDP <- read_excel("/Users/ankushi/Desktop/GOVT-772_Data_Science/assignment04/gdp_AB.xlsx")
country_labels <- read_excel("/Users/ankushi/Desktop/GOVT-772_Data_Science/assignment04/labelfile_AB.xlsx")

# descriptive data on Q4A: how would you describe the present economic situation of the country?
AB %>% count(Q4A) #dropping missing (-1), "refused" (8), and "dont know" (9) values 
group_by(AB, Q4A) 
AB <- AB %>%
  filter(Q4A<8, Q4A>-1) 
summarize(AB, mean(Q4A), sd(Q4A), fivenum(Q4A))

#mean value of economic evaluation by country 
df2 <- AB %>% group_by(COUNTRY) %>%
  summarise(mean(Q4A)) %>%
  print(n=34)

#combining separate label file from Afrobarometer and GDP data from World Bank microdata catalog 
df3 <- bind_cols(country_labels$country_lbl, df2$COUNTRY, df2$`mean(Q4A)`, GDP$`GDP (Current US$, 2020)`) 
df3 <- rename(df3, country_lbl = ...1, country = ...2, avg = ...3, gdp = ...4)

theme_set(theme_fivethirtyeight())
econ_gdp <- ggplot(df3, aes(x=gdp, y=avg)) + 
  geom_point(alpha = 0.01) + 
  geom_text(aes(label=country_lbl), size=2, check_overlap = TRUE) +
  labs(
    title = "Evaluation of Country's Present Economic Situation (Very Bad to Very Good)",
    subtitle = "By GDP (2020, US$)",
    caption = "Sources: Afrobarometer R7; World Bank",
    x = "GDP (2020, US$)",
    y = "Opinion on Country's Present Economic Situation (Very Bad to Very Good)"
  ) + 
  theme(
    plot.title = element_text(color = "grey35", size = 10, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 8, hjust = 0.5),
    plot.caption = element_text(face = "italic", size = 6, hjust = 1), 
  ) +
  theme(axis.text.x = element_text(size=7), 
        axis.text.y = element_text(size=7),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8)) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    plot.background = element_blank()) +
  scale_x_log10(labels = label_number(suffix = "B", scale = 1e-9))
econ_gdp

```


##Visualization 2 (Comparison)

```{r}

theme_set(theme_fivethirtyeight())
econ_gdp_smoothed <- ggplot(df3, aes(x=gdp, y=avg)) + 
  geom_point(alpha = 0.01) + 
  geom_text(aes(label=country_lbl), size=2, check_overlap = TRUE) +
  geom_smooth(inherit.aes = TRUE) +
  labs(
    title = "Opinions on Country's Present Economic Situation (Very Bad to Very Good)",
    subtitle = "By GDP (2020, US$)",
    caption = "Sources: Afrobarometer R7; World Bank",
    x = "GDP (2020, US$)",
    y = "Opinion on Country's Present Economic Situation (Very Bad to Very Good)"
  ) + 
  theme(
    plot.title = element_text(color = "grey35", size = 9, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 8, hjust = 0.5),
    plot.caption = element_text(face = "italic", size = 6, hjust = 1), 
  ) +
  theme(axis.text.x = element_text(size=7), 
        axis.text.y = element_text(size=7),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8)) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    plot.background = element_blank()) +
  scale_x_log10(labels = label_number(suffix = "B", scale = 1e-9))
econ_gdp_smoothed


GDPPC <- read_excel("/Users/ankushi/Desktop/GOVT-772_Data_Science/assignment04/gdpPC_AB.xlsx")
df3 <- bind_cols(df3, GDPPC)

theme_set(theme_fivethirtyeight())
econ_gdppc <- ggplot(df3, aes(x=`GDP Per Capita`, y=avg)) + 
  geom_point(alpha = 0.01) + 
  geom_text(aes(label=country_lbl), size=2, check_overlap = TRUE) +
  geom_smooth(inherit.aes = TRUE) +
  labs(
    title = "Opinions on Country's Present Economic Situation (Very Bad to Very Good)",
    subtitle = "By GDP Per Capita (2020, US$)",
    caption = "Sources: Afrobarometer R7; World Bank",
    x = "GDP Per Capita (2020, US$)",
    y = "Opinion on Country's Present Economic Situation (Very Bad to Very Good)"
  ) + 
  theme(
    plot.title = element_text(color = "grey35", size = 9, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 8, hjust = 0.5),
    plot.caption = element_text(face = "italic", size = 6, hjust = 1)) +
  theme(axis.text.x = element_text(size=7), 
        axis.text.y = element_text(size=7),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8)) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    plot.background = element_blank()) 
econ_gdppc
  

```

##Visualization 3

```{r}


AB <- read_sav("/Users/ankushi/Desktop/GOVT-772_Data_Science/assignment04/AB_R7_Merged")

# descriptive data on Q4A: how would you describe the present economic situation of the country?
AB %>% count(Q4A) #dropping missing (-1), "refused" (8), and "dont know" (9) values 
group_by(AB, Q4A) 
AB <- AB %>%
  filter(Q4A<8, Q4A>-1) 

AB %>% count(URBRUR) #dropping obvs. coded as "semi urban" and "peri urban" since they are a small proportion of the sample
AB <- AB %>%
  filter(URBRUR<3) 


theme_set(theme_fivethirtyeight()) 
ggplot() +
  geom_bar(data = AB, (aes(x = Q4A, group = URBRUR, fill = factor(URBRUR))), position = "dodge") +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    plot.background = element_blank()) +
  labs(
    title = "Opinions on Country's Present Economic Condition",
    subtitle = "By Location",
    caption = "Source: Afrobarometer R7",
    x = "Opinions on Economic Condition",
    y = "Number of Respondents") +
  theme(
    plot.title = element_text(color = "grey35", size = 10, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 8, hjust = 0.5),
    plot.caption = element_text(face = "italic", size = 5, hjust = 1)) +
  theme(axis.text.x = element_text(size=5), 
        axis.text.y = element_text(size=5), 
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8)) +
  scale_fill_discrete(name = "Location", labels = c("Urban", "Rural")) +
  theme(legend.title = element_blank(),
        legend.background = element_blank(),
        legend.key = element_blank(),
        legend.key.size = unit(0.3, "cm"),
        legend.text = element_text(size = 8)) +
  scale_x_continuous(breaks=c(1,2,3,4,5), 
                     labels=expression("Very Bad", "Fairly Bad",
                                       "Neither", "Fairly Good", "Very Good"))

```

##Visualization 4

```{r}

AB <- read_sav("/Users/ankushi/Desktop/GOVT-772_Data_Science/assignment04/AB_R7_Merged")

AB %>% count(Q4A) #dropping missing (-1), "refused" (8), and "dont know" (9) values 
AB <- AB %>%
  filter(Q4A<8, Q4A>-1) 

AB %>% count(Q29) #dropping missing (-1), "refused" (8), "dont know" (9), and "neither" (5) values 
AB <- AB %>%
  filter(Q29<5, Q29 > -1) 

theme_set(theme_fivethirtyeight()) 
AB %>% ggplot() +
  geom_jitter(aes(x=Q4A, y=Q29), size=0.3, color="#91b8bd") +
  theme(
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(), 
  plot.background = element_blank()) +
  labs(
    title = "Is It More Important To Have A Government That Can Get Things Done, 
    Even If We Have No Influence Over What It Does?",
    subtitle = "By Assessment of Country's Present Economic Condition",
    caption = "Source: Afrobarometer R7",
    x = "Assessment of Economic Conditions (Very Bad to Very Good)",
    y = "Support for Democratic Accountability (Less Supportive to More Supportive)") +
  theme(
    plot.title = element_text(color = "grey35", size = 8.5, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 7.5, hjust = 0.5),
    plot.caption = element_text(face = "italic", size = 5, hjust = 1)) +
  theme(axis.text.x = element_text(size=7), 
        axis.text.y = element_text(size=7), 
        axis.title.x = element_text(size=7),
        axis.title.y = element_text(size=7)) 

```


